#!/bin/sh
# build identity of the fork. first hit wins:
#   $RWNX_VERSION_IDENTITY -> git describe -> $ROOT/VERSION
# modes: identity | --base (vendor baseline) | --header
set -eu

MODE="${1:-identity}"
case "$MODE" in
    identity|--base|--header) ;;
    *) echo "usage: $0 [identity|--base|--header]" >&2; exit 2 ;;
esac

# -P: physical path; rev-parse reports physical paths (/var -> /private/var)
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
# describe/rev-parse walk up to any enclosing .git; trust only when $ROOT
# is exactly that toplevel (a staged/DKMS tree may sit inside one)
TOP=$(git -C "$ROOT" rev-parse --show-toplevel 2>/dev/null || true)

identity=""
if [ -n "${RWNX_VERSION_IDENTITY:-}" ]; then
    identity="$RWNX_VERSION_IDENTITY"
elif [ -n "$TOP" ] && [ "$TOP" = "$ROOT" ] && V=$(git -C "$ROOT" describe --tags --dirty 2>/dev/null); then
    identity="$V"
elif [ -f "$ROOT/VERSION" ]; then
    identity=$(tr -d '[:space:]' < "$ROOT/VERSION")
fi
if [ -z "$identity" ]; then
    echo "ERROR: no build identity. set RWNX_VERSION_IDENTITY, put a v<version>" \
         "tag in $ROOT, or write $ROOT/VERSION" >&2
    exit 1
fi

# allow one leading v (git tag form). then whitelist: dotted version plus
# -alnum suffixes (post-tag count/hash, dirty). anything else (quotes,
# backslash, newline, garbage) is rejected - identity flows into #define
# string literals of the generated header
identity="${identity#v}"
if ! printf '%s' "$identity" | grep -Eq '^[0-9]+(\.[0-9]+)*(-[0-9A-Za-z]+)*$'; then
    echo "ERROR: malformed build identity '$identity'" >&2
    exit 1
fi

# vendor baseline = up to first hyphen (same rule as the release gate)
base="${identity%%-*}"

case "$MODE" in
    identity) printf '%s\n' "$identity" ;;
    --base)   printf '%s\n' "$base" ;;
    --header)
        if [ "$TOP" = "$ROOT" ]; then
            GITHASH=$(git -C "$ROOT" rev-parse --short=7 HEAD)
        else
            GITHASH=nogit
        fi
        RELEASE_DATE="$(date -u +%Y_%m%d)_${GITHASH}"
        BANNER="rwnx ${identity} (vendor base ${base}, fork: ronnyf/AIC8800-Linux-Driver)"
        # aic_vendor.c memcpy's this into char[128]; hard cap, no heuristic
        BANNER=$(printf '%s' "$BANNER" | cut -c1-127)
        cat <<EOF
/* Generated by tools/gen_version.sh - do not edit, do not commit. */
#define RWNX_VERS_MOD "${base}"
#define RWNX_VERS_BANNER "${BANNER}"
#define RELEASE_DATE "${RELEASE_DATE}"
EOF
        ;;
esac
