#!/bin/sh
# Print the build identity of the AIC8800 driver fork.
#
# Identity chain (first hit wins; a failed git describe falls THROUGH, it does
# not error just because .git exists):
#   1. $RWNX_VERSION_IDENTITY       (exported by CI from the release tag)
#   2. git describe --tags [dirty]  (only when it actually succeeds)
#   3. $ROOT/VERSION                (release tarball / DKMS tree)
#
# Modes:
#   (none)      print the identity string, e.g. 6.4.3.0-8
#   --base      print the vendor baseline, e.g. 6.4.3.0
#   --header    print the rwnx_version_gen.h content on stdout
#
# ROOT is derived from this script's own location, so it works from the git
# repo (tools/ at repo root) and from a staged/DKMS tree (tools/ at root).
set -eu

MODE="${1:-identity}"
case "$MODE" in
    identity|--base|--header) ;;
    *) echo "usage: $0 [identity|--base|--header]" >&2; exit 2 ;;
esac

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

identity=""
if [ -n "${RWNX_VERSION_IDENTITY:-}" ]; then
    identity="$RWNX_VERSION_IDENTITY"
elif V=$(git -C "$ROOT" describe --tags --dirty 2>/dev/null); then
    identity="${V#v}"
elif [ -f "$ROOT/VERSION" ]; then
    identity=$(tr -d '[:space:]' < "$ROOT/VERSION")
fi
if [ -z "$identity" ]; then
    echo "ERROR: no build identity. Set RWNX_VERSION_IDENTITY, build in a git" \
         "repository with a reachable v<version> tag, or provide $ROOT/VERSION" >&2
    exit 1
fi

# Vendor baseline = identity up to (not including) the first "-<N>" fork
# revision, stable across release, post-tag, and dirty identities alike, and
# agnostic to how many dotted components the vendor baseline itself has (it
# has been four so far; check_release_version.sh's dkms.conf check uses this
# same "strip from the first hyphen" rule, so the two stay in lockstep if
# AICSemi ever ships a differently-shaped version).
base="${identity#v}"
base="${base%%-*}"
if [ -z "$base" ]; then
    echo "ERROR: cannot parse vendor baseline from identity '$identity'" >&2
    exit 1
fi

case "$MODE" in
    identity) printf '%s\n' "$identity" ;;
    --base)   printf '%s\n' "$base" ;;
    --header)
        GITHASH=$(git -C "$ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo nogit)
        RELEASE_DATE="$(date -u +%Y_%m%d)_${GITHASH}"
        BANNER="rwnx ${identity} (vendor base ${base}, fork: ronnyf/AIC8800-Linux-Driver)"
        # The vendor command copies the banner into char[128] (aic_vendor.c);
        # never emit one it cannot hold.
        if [ "$(printf '%s' "$BANNER" | wc -c | tr -d '[:space:]')" -ge 128 ]; then
            BANNER="rwnx ${base} (vendor base ${base}, fork: ronnyf/AIC8800-Linux-Driver)"
        fi
        cat <<EOF
/* Generated by tools/gen_version.sh - do not edit, do not commit. */
#define RWNX_VERS_MOD "${base}"
#define RWNX_VERS_BANNER "${BANNER}"
#define RELEASE_DATE "${RELEASE_DATE}"
EOF
        ;;
esac
